#%RAML 0.8

title: World Music API
baseUri: https://cryptic-earth-32410.herokuapp.com/
version: v1

/users/{user_id}/followers:
  get:
    responses:
      200:
        body:
          application/json:
            schema: |
              { "$schema": "http://json-schema.org/schema",
                "type": "object",{
                  "description": "A follower",
                  "properties": {
                      "_links": { 
                        "type": "object",
                        "description": "Links",
                        "properties" : {
                          "previous": "string",
                          "self": "string",
                          “next”: "string"
                        }
                    },
                    "_embedded" :{
                      "type": "array",
                      "items": {
                        "type" : "object",
                        "properties" : {
                          "id": "integer"
                        }
                      }
                    }
                  }
              }